version: '3.5'
services:
  workshop14app:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - redisdb
    links:
      - "redisdb"
    networks:
      - some-net #

  redisdb:
    image: "redis:alpine"
    hostname: redisdb
    ports:
     - "6379:6379"
    networks:
      - some-net #
  
networks:
  some-net:
    driver: bridge

