FROM openjdk:17-jdk-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG DEPENDENCY=target/
COPY ${DEPENDENCY}/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","sg.edu.nus.workshop14.Workshop14Application"]